FROM wordpress:cli-php8.0

LABEL title="CLI-LMS"

COPY commands.sh /commands.sh
#ADD commands.sh /commands.sh
RUN chmod +x /commands.sh \
CMD  ["/commands.sh"]
#ENTRYPOINT ["/commands.sh"]
#USER 33:33